Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load data set
data = arff.loadarff("/content/drive/MyDrive/datamining/tugas/notebooks-assignement/asset/messidor_features.arff")
------------------

[0;31m[0m
[0;31mFileNotFoundError[0mTraceback (most recent call last)
[0;32m<ipython-input-2-ec093bc00150>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# load data set[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdata[0m [0;34m=[0m [0marff[0m[0;34m.[0m[0mloadarff[0m[0;34m([0m[0;34m"/content/drive/MyDrive/datamining/tugas/notebooks-assignement/asset/messidor_features.arff"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/local/lib/python3.7/dist-packages/scipy/io/arff/arffread.py[0m in [0;36mloadarff[0;34m(f)[0m
[1;32m    798[0m         [0mofile[0m [0;34m=[0m [0mf[0m[0;34m[0m[0;34m[0m[0m
[1;32m    799[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 800[0;31m         [0mofile[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mf[0m[0;34m,[0m [0;34m'rt'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    801[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    802[0m         [0;32mreturn[0m [0m_loadarff[0m[0;34m([0m[0mofile[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/datamining/tugas/notebooks-assignement/asset/messidor_features.arff'
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/datamining/tugas/notebooks-assignement/asset/messidor_features.arff'

